### ISSUE TITLE
GoogleAuth invalid_grant

### ISSUE THREAD

**Issue by javieralcantara** [VictorRancesCode/flutter_dialogflow#26]
I used the firebase JSON file by mistake for another project. After it my original project throws that error when importing the dialogflow JSON file (GoogleAuth method). I tried refreshing the dialogflow service account. That generated a key I can’t download. All I can do is create a new key and import that one. The error persists. 

https://blog.timekit.io/google-oauth-invalid-grant-nightmare-and-how-to-fix-it-9f4efaf1da35

**Comment by javieralcantara** [comment]
`AuthGoogle authGoogle = await AuthGoogle(fileJson: "assets/glasgow-caledonian-assistant-33617a88b766.json", sessionId: userUID).build().catchError(
      (onError) {
        print(onError);
      });`
That returns:
`E/flutter (10773): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'getP
rojectId' was called on null.
E/flutter (10773): Receiver: null
E/flutter (10773): Tried calling: getProjectId
E/flutter (10773): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter (10773): #1      Dialogflow._getUrl (package:flutter_dialogflow/v2/dialogflow_v2.dart:114:72)
E/flutter (10773): #2      Dialogflow.detectIntent (package:flutter_dialogflow/v2/dialogflow_v2.dart:118:42)
E/flutter (10773): #3      _HomePageDialogflowV2.response (package:gcu/screens/home/home.dart:71:44)
E/flutter (10773): <asynchronous suspension>
E/flutter (10773): #4      _HomePageDialogflowV2._handleSubmitted (package:gcu/screens/home/home.dart:92:5)
E/flutter (10773): #5      _HomePageDialogflowV2._buildTextComposer.<anonymous closure> (package:gcu/screens/home/home.d
art:56:36)
E/flutter (10773): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
E/flutter (10773): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:3
6)
E/flutter (10773): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (10773): #9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
E/flutter (10773): #10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
E/flutter (10773): #11     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199:7)
E/flutter (10773): #12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:467
:9)
E/flutter (10773): #13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter (10773): #14     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointe
r_router.dart:117:9)
E/flutter (10773): #15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter (10773): #16     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18
)
E/flutter (10773): #17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)
E/flutter (10773): #18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (10773): #19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (10773): #20     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (10773): #21     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (10773): #22     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (10773): #23     _rootRunUnary (dart:async/zone.dart:1138:13)
E/flutter (10773): #24     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (10773): #25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter (10773): #26     _invoke1 (dart:ui/hooks.dart:273:10)
E/flutter (10773): #27     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
E/flutter (10773):`
